# Generated by Django 2.1.7 on 2019-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fcs_files')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
