# Generated by Django 2.1.7 on 2019-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_task_taskimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCSFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='Files/FCS_RAW/')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.RemoveField(
            model_name='taskimage',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
